certificates:
  beaconchain.withdrawal-mainnet-shadowfork-1.ethpandaops.io:
    mode: http
  ethstats.withdrawal-mainnet-shadowfork-1.ethpandaops.io:
    mode: http

haproxy_frontends:
  - name: host_mainnet_beacon
    address: beaconchain.withdrawal-mainnet-shadowfork-1.ethpandaops.io
    backend: host_mainnet_beacon
  - name: host_msf_ethstats
    address: ethstats.withdrawal-mainnet-shadowfork-1.ethpandaops.io
    backend: host_msf_ethstats

haproxy_backend_servers:
  - name: host_mainnet_beacon
    address: 127.0.0.1:3333
    options: 'check fall 3 rise 2'
  - name: host_msf_ethstats
    address: 127.0.0.1:3000
    options: 'check fall 3 rise 2'

haproxy_stats_port: 8404
haproxy_user: devops
haproxy_group: devops
haproxy_stats_user: devops
haproxy_stats_password: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/verkle/verkle-haproxy-key') }}"

haproxy_default_backend_name: host_mainnet_beacon
grafana_prometheus_network_name: explorernet

le_email: parithosh@ethereum.org
debian_certbot: false
