txfuzz_container_name: tx-fuzz
txfuzz_image_name: ethpandaops/tx-fuzz:latest

rpc_url: https://rpc.withdrawal-devnet-4.ethpandaops.io
txfuzz_private_key: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/withdrawals/devnet1/tx-fuzz-key') }}"
txfuzz_public_key: "0x2cA5F489CC1Fd1CEC24747B64E8dE0F4A6A850E1"

txfuzz_start_args: "spam --no-al --seed={{chainID}} --sk={{txfuzz_private_key}} --rpc={{rpc_url}} --txcount 1"