roles:
- name: cloudalchemy.node_exporter
  version: "2.0.0"
- name: cloudalchemy.prometheus
  version: "2.16.2"
- name: gantsign.oh-my-zsh
  version: "2.4.0"
- name: geerlingguy.docker
  version: "4.2.3"
- name: geerlingguy.firewall
  version: "2.5.0"
- name: robertdebock.bootstrap
  version: "6.1.1"
- name: robertdebock.fail2ban
  version: "4.2.3"
- name: ansible-haproxy
  src:  https://github.com/parithosh/ansible-haproxy
  version: 8b60485f53a1f5b385764d132028c550595abc71
  scm: git

collections:
  - name: ethpandaops.ethereum
    source: https://github.com/skylenet/ethereum-ansible.git,skylenet/beaconchain-explorer-aio
    type: git
