certificates:
  rpc.withdrawal-devnet-6.ethpandaops.com:
    mode: http
  withdrawal-devnet-6.ethpandaops.com:
    mode: http
  faucet.withdrawal-devnet-6.ethpandaops.com:
    mode: http
  explorer.withdrawal-devnet-6.ethpandaops.com:
    mode: http
  ethstats.withdrawal-devnet-6.ethpandaops.com:
    mode: http
  beaconchain.withdrawal-devnet-6.ethpandaops.com:
    mode: http
  forkmon.withdrawal-devnet-6.ethpandaops.com:
    mode: http

haproxy_frontends:
  - name: host_withdrawal_devnet_rpc
    address: rpc.withdrawal-devnet-6.ethpandaops.com
    backend: host_withdrawal_devnet_rpc
  - name: host_withdrawal_devnet
    address: withdrawal-devnet-6.ethpandaops.com
    backend: host_withdrawal_devnet
  - name: host_withdrawal_devnet_faucet
    address: faucet.withdrawal-devnet-6.ethpandaops.com
    backend: host_withdrawal_devnet_faucet
  - name: host_withdrawal_devnet_explorer
    address: explorer.withdrawal-devnet-6.ethpandaops.com
    backend: host_withdrawal_devnet_explorer
  - name: host_withdrawal_devnet_ethstats
    address: ethstats.withdrawal-devnet-6.ethpandaops.com
    backend: host_withdrawal_devnet_ethstats
  - name: host_withdrawal_devnet_beaconchain
    address: beaconchain.withdrawal-devnet-6.ethpandaops.com
    backend: host_withdrawal_devnet_beaconchain
  - name: host_withdrawal_devnet_forkmon
    address: forkmon.withdrawal-devnet-6.ethpandaops.com
    backend: host_withdrawal_devnet_forkmon

haproxy_backend_servers:
  - name: host_withdrawal_devnet_rpc
    address: 127.0.0.1:8545
    options: 'check fall 3 rise 2'
  - name: host_withdrawal_devnet
    address: 127.0.0.1:1313
    options: 'check fall 3 rise 2'
  - name: host_withdrawal_devnet_faucet
    address: 127.0.0.1:8010
    options: 'check fall 3 rise 2'
  - name: host_withdrawal_devnet_explorer
    address: 127.0.0.1:3334
    options: 'check fall 3 rise 2'
  - name: host_withdrawal_devnet_ethstats
    address: 127.0.0.1:3000
    options: 'check fall 3 rise 2'
  - name: host_withdrawal_devnet_beaconchain
    address: withdrawal-devnet-6-explorer-1.ethpandaops.com:8080
    options: 'check fall 3 rise 2'
  - name: host_withdrawal_devnet_forkmon
    address: 127.0.0.1:8181
    options: 'check fall 3 rise 2'

haproxy_stats_port: 8404
haproxy_user: devops
haproxy_group: devops
haproxy_stats_user: devops
haproxy_stats_password: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/verkle/verkle-haproxy-key') }}"

haproxy_default_backend_name: host_withdrawal_devnet
grafana_prometheus_network_name: explorernet

le_email: bbusa@ethereum.org
debian_certbot: false
