- name: Move data dirs to backup, get ready for resync
  hosts: beacon
  gather_facts: true
  serial: 20
  tasks:
#    - name: Rm the el data dir
#      become: true
#      shell: "rm -rf {{el_node_dir}}"
#    - name: Rm the beacon data dir
#      become: true
#      shell: "rm -rf {{beacon_node_dir}}"
    - name: Move the beacon data dir
      become: true
      shell: "mv {{beacon_node_dir}} {{beacon_node_dir}}_old"
    - name: Move the el data dir
      become: true
      shell: "mv {{el_node_dir}} {{el_node_dir}}_old"

