- name: Start explorer docker net
  hosts: explorer
  gather_facts: true
  serial: 20
  tasks:
    # postgres on 172.28.0.100
    # explorer on 172.28.0.101
    # beacon   on 172.28.0.102
    # el       on 172.28.0.103   # removed for Altair purposes, used in Merge
    # explorerstats on 172.28.0.104
    - name: Create explorer net
      docker_network:
        name: "{{explorer_docker_network_name}}"
        ipam_config:
          - subnet: 172.28.0.0/24
            gateway: 172.28.0.1
            iprange: 172.28.0.0/24
