##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"
initial_remote_user: "root"

github_user_pubkeys:
  - parithosh
  - barnabasbusa
  - skylenet
  - samcm
  - savid
  - infosecual
  

ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"

##############################################
# el endpoints
##############################################
# nimbus requires a websocket endpoint (http support unstable)
# note: also used for execution engine endpoint in nimbus
consensus_endpoint_nimbus: ws://127.0.0.1:8551
beacon_api_endpoint: "http://127.0.0.1:{{beacon_api_port}}"
elendpoint: http://127.0.0.1:8545

# Merge Engine endpoints
# TODO change IP?
# TODO: some engines might start using the 8550 port (or 8551 for ws)

##############################################
# testnet specific information
##############################################
testnet_type: custom
cl_network_name: withdrawal-devnet-5
chainID: 1337809
fee_recipient: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"
upload_bls_keys: true
# enter bootnodes here if needed
bootnode_enrs:
  - "enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk"
  - "enr:-Ly4QOUsHZ_lewoMmnlS7l49yd5I_kxWfMVi1ei8AmuS9NcxWKPBb44fBh_6FKuQiG6mKRG18aIdRHgH6gTbq3Lmnc0Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAjJ3vzQAAAQhQAAAAAAAAAgmlkgnY0gmlwhJK-4RWJc2VjcDI1NmsxoQOsOdWP2sD1YUxtopnn_942X301b1zF76QYfljE0nHsEohzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"
  - "enr:-Ly4QFqJOk5k86FHmYWGoGl9M7GPjfO23ymMKD6Euzd2wryMfDysU7BXzKqsEilVxwkO9urTSdB5LB3Z9yW4dnpWbLABh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAjJ3vzQAAAQhQAAAAAAAAAgmlkgnY0gmlwhIDHPjWJc2VjcDI1NmsxoQISCG4TTlh9DKpiyKRrbVfOk67pSZJ2WZKNqCzy1QmB8IhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"
  - "enr:-Ly4QP2rdu0ZK10YKN9wI65PqQSEDpvgfbbubEWYr5irVIUYesP6Q1HaixYeG8aWLyU6xOE9V5NDb8BEkqyk_CWJMxMBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAjJ3vzQAAAQhQAAAAAAAAAgmlkgnY0gmlwhLymGueJc2VjcDI1NmsxoQMNz90w3qxWfDv5TrCtdnLbfdaQnCU7hqSoVqWKp8cHuohzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"
  - "enr:-Ly4QBedUMMxbAE6Evqcunj96CiD0-_GuWtdURMhEMd2Uw3GI_f3ORx3lrgsR7zSJf0qj3mLsGWSiv6hlJBvBkMUbTIBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAjJ3vzQAAAQhQAAAAAAAAAgmlkgnY0gmlwhIDHPteJc2VjcDI1NmsxoQLSfROTsdbPDTeMCIkDlJ4hXt5rFAXH0Wr1z0EsRcKYDYhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"
multiaddrs: 
  - "/ip4/146.190.225.21/tcp/9000/p2p/16Uiu2HAmQFHd7o3UqBEWzmtCim4LHXvJpHF2rCmZEqRFrufzrTgV"
  - "/ip4/128.199.62.215/tcp/9000/p2p/16Uiu2HAm9bLDQqBbcs5EbqFgzSV7RNH7Vh3WsGvwDHEY18yR7ttc"
  - "/ip4/188.166.26.231/tcp/9000/p2p/16Uiu2HAmDauVBWJNx6pf579riVhm5h9Dw31Z5QCiStkDuhUZahYD"
  - "/ip4/128.199.62.53/tcp/9000/p2p/16Uiu2HAkve4mrFueVM9VoY8DKGew8beFcngSSosWewjuQ3tov4By"
el_bootnode_enode:
  - "enode://66c10b14aa42ef2d00f6ddce53451e48aac41ab0983f0b0c2585cc74d5f6e02e7435337bdf8dc9f20a86fdec4cd2f7ac30ce6cb7276c728200086ca9a3e03645@146.190.225.21:30303"
  - "enode://002486dab1901d6eb83c73eeb20a790466d81a3e01beb01bbe2084e7d9842d84e660e4735327c45d74802f00c7f7d8ac4f7060dd62684d224cdaf7544e776d5c@188.166.26.231:30303"
  - "enode://8ed6b2bbb3b0a370ae97fb081e6ab24dbc7620a819420a8eee32b206156a57ad57bc8092c1cae7412b57b1696a8de046bd54b796c9b597573fc119b411cd333b@128.199.62.215:30303"
  - "enode://03d1aef6f6afb35b4578bdfcdd5cf96a91a238b38207ff5c5056c433da733f50483f27db3178f3f568468eb14acf530694187fd9eb53c5f2afab9b2f7c2d71f0@128.199.62.53:30303"
el_static_enodes: "{{el_bootnode_enode}}"
##############################################
# metric information
##############################################
# enter pushgateway config if needed
prometheus_config_file: "prometheus/prometheus.yml.j2"
push_url: "https://victoriametrics.ethdevops.io/insert/0/prometheus/api/v1/write"
metrics_enabled: true
push_metrics_enabled: true
remote_write_auth: true
eth_metrics_exporter_enabled: true
cl_validator_metrics_enabled: false
eth_metrics_exporter_name: "metrics-exporter"
eth_metrics_exporter_image: "ethpandaops/ethereum-metrics-exporter:0.19.0"
remote_write_username: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/withdrawal-devnet-5.json | jq .username') }}"
remote_write_password: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/eth2/monitoring/observability-cluster/metrics-ingress-users/withdrawal-devnet-5.json | jq .password') }}"


no_validator_keys: false
ethstats_enabled: false
metrics_enabled: false
snapsync_enabled: false
ethstats_url: "example.io"
ethstats_password: "example"

##############################################
# mev boost configs
##############################################
mev_boost_image_name: flashbots/mev-boost:v1.4.0
mev_boost_container_name: mev_boost
mev_boost_start_args: "-genesis-fork-version 0x00 -relays http://example.io"
mev_boost: false

##############################################
# ports to configure
##############################################
el_rpc_port: 8545
el_ws_rpc_port: 8546
el_engine_port_no_auth: 8550
el_engine_port: 8551
el_engine_snoop_port: 8560
el_engine_ws_port: 8552
nimbus_rpc_port: 4009
beacon_api_port: 4000
beacon_grpc_port: 4001
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
node_exporter_web_listen_address: "127.0.0.1:9100"
prometheus_web_listen_address: "127.0.0.1:9101"
el_metrics_port: 8002
eth_metrics_exporter_port: 8003
mev_boost_port: 18550

##############################################
# Command for JSON RPC snooper
##############################################
snoop_image_name: parithoshj/json_rpc_snoop:v1.0.0-x86
snoop_container_name: snooper

##############################################
# name of the validator to display
##############################################
graffiti: "{{cl_client_name}}-{{el_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
local_cl_config_filepath: "{{local_custom_config_data_host_dir}}/config.yaml"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}"
local_validator_host_archive: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}.tar.gz"

##############################################
# remote host data directories
##############################################
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"
testnet_dir: "{{home_dir}}/custom_config_data"
el_node_dir: "{{home_dir}}/eldata"

##############################################
# common log config
# Possible log levels:
# silent, error, warn, info (default), debug, detail
##############################################
execution_log_level: info
beacon_log_level: info
common_log_options:
  max-file: "10"
  max-size: 500m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file


##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
execution_container_name: execution
hi_peer_count: 100
separate_validator_process_enabled: true

firewall_allowed_tcp_ports:
  - 22
  - 30303
  - 9000
  - 80
  - 443
  - 8545
  - 8546
  - 4000

firewall_allowed_udp_ports:
  - 30303
  - 9000
  - 80
  - 443
  - 53

firewall_flush_rules_and_chains: true

firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 8545 -s 172.16.0.0/12 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8546 -s 172.16.0.0/12 -j ACCEPT"