certificates:
  rpc.withdrawal-devnet-5.ethpandaops.io:
    mode: http
  withdrawal-devnet-5.ethpandaops.io:
    mode: http
  faucet.withdrawal-devnet-5.ethpandaops.io:
    mode: http
  explorer.withdrawal-devnet-5.ethpandaops.io:
    mode: http
  ethstats.withdrawal-devnet-5.ethpandaops.io:
    mode: http
  beaconchain.withdrawal-devnet-5.ethpandaops.io:
    mode: http
  forkmon.withdrawal-devnet-5.ethpandaops.io:
    mode: http

haproxy_frontends:
  - name: host_withdrawal_devnet_5_rpc
    address: rpc.withdrawal-devnet-5.ethpandaops.io
    backend: host_withdrawal_devnet_5_rpc
  - name: host_withdrawal_devnet_5
    address: withdrawal-devnet-5.ethpandaops.io
    backend: host_withdrawal_devnet_5
  - name: host_withdrawal_devnet_5_faucet
    address: faucet.withdrawal-devnet-5.ethpandaops.io
    backend: host_withdrawal_devnet_5_faucet
  - name: host_withdrawal_devnet_5_explorer
    address: explorer.withdrawal-devnet-5.ethpandaops.io
    backend: host_withdrawal_devnet_5_explorer
  - name: host_withdrawal_devnet_5_ethstats
    address: ethstats.withdrawal-devnet-5.ethpandaops.io
    backend: host_withdrawal_devnet_5_ethstats
  - name: host_withdrawal_devnet_5_beaconchain
    address: beaconchain.withdrawal-devnet-5.ethpandaops.io
    backend: host_withdrawal_devnet_5_beaconchain
  - name: host_withdrawal_devnet_5_forkmon
    address: forkmon.withdrawal-devnet-5.ethpandaops.io
    backend: host_withdrawal_devnet_5_forkmon

haproxy_backend_servers:
  - name: host_withdrawal_devnet_5_rpc
    address: 127.0.0.1:8545
    options: 'check fall 3 rise 2'
  - name: host_withdrawal_devnet_5
    address: 127.0.0.1:1313
    options: 'check fall 3 rise 2'
  - name: host_withdrawal_devnet_5_faucet
    address: 127.0.0.1:8010
    options: 'check fall 3 rise 2'
  - name: host_withdrawal_devnet_5_explorer
    address: 159.223.223.83:3334
    options: 'check fall 3 rise 2'
  - name: host_withdrawal_devnet_5_ethstats
    address: 127.0.0.1:3000
    options: 'check fall 3 rise 2'
  - name: host_withdrawal_devnet_5_beaconchain
    address: withdrawal-devnet-5-explorer-1.ethpandaops.io:8080
    options: 'check fall 3 rise 2'
  - name: host_withdrawal_devnet_5_forkmon
    address: 127.0.0.1:8181
    options: 'check fall 3 rise 2'

haproxy_stats_port: 8404
haproxy_user: devops
haproxy_group: devops
haproxy_stats_user: devops
haproxy_stats_password: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/verkle/verkle-haproxy-key') }}"

haproxy_default_backend_name: host_withdrawal_devnet_5
grafana_prometheus_network_name: explorernet

le_email: bbusa@ethereum.org
debian_certbot: false
