##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"
initial_remote_user: "root"

github_user_pubkeys:
  - parithosh
  - holgerd77
  - jochem-brouwer
  - alcuadrado

ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"

##############################################
# el endpoints
##############################################
# nimbus requires a websocket endpoint (http support unstable)
# note: also used for execution engine endpoint in nimbus
consensus_endpoint_nimbus: ws://127.0.0.1:8551
beacon_api_endpoint: "http://127.0.0.1:{{beacon_api_port}}"
elendpoint: http://127.0.0.1:8545

# Merge Engine endpoints
# TODO change IP?
# TODO: some engines might start using the 8550 port (or 8551 for ws)

##############################################
# testnet specific information
##############################################
testnet_type: custom
cl_network_name: shandong-testnet
chainID: 1337902
terminal_total_difficulty: "0"
fee_recipient: "0xf97e180c050e5Ab072211Ad2C213Eb5AEE4DF134"
# enter bootnodes here if needed
bootnode_enrs:
  - "enr:-MS4QI4QsRpZ04IOeViMGm_ewxcM6RZKKSTcSOA4rbW8lGIDNzGDsTponl-Anj-5f4S0u6PD4vGk1jEPCZdYhHF9Ph8Ih2F0dG5ldHOIAAAAAAAAAACEZXRoMpA6j89cITN5Av__________gmlkgnY0gmlwhC5lfi2Jc2VjcDI1NmsxoQO1gCnLpNNWvsJfDUoXM8x0oRX-RqJHh8f2XcYFWgk55IhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo"
  - "enr:-MS4QDCCUxgq8mjTKU8Dsi9Gici2dF0P9D9VouDcTlsOZ4liK4OBH1uaG8mYFVKbj-cIK0-9l-5F9RvF4CZOKKSIGkkIh2F0dG5ldHOIAAAAAAAAAACEZXRoMpA6j89cITN5Av__________gmlkgnY0gmlwhI5dYGSJc2VjcDI1NmsxoQIO83376GBdlDIEQ3wPqqQThrKjaD_35Kiw33IRLqmbA4hzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo"
  - "enr:-MS4QHcxDzDf5VYOccJQ2UyQdZKDdaNejyOJiTmaW68Yrev1Gq3SA3NjOuEJeSAAUWgLMbTouiVhpcNRSw7A8g7QuAcIh2F0dG5ldHOIAAAAAAAAAACEZXRoMpA6j89cITN5Av__________gmlkgnY0gmlwhLKAzkyJc2VjcDI1NmsxoQN4wOyy46btWLAklY6vyCsCT8XSNBiGzhD0v5dkBeXQ_YhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo"
  - "enr:-MS4QOPIk5ZnV1JPkzjFXHbcD2I7Y5XK1HpQTuNSnjBSw6n1INU_z3i_iI-zPfcWcKWQdF5HnW85Y8nRPanw5eXFgDYIh2F0dG5ldHOIAAAAAAAAAACEZXRoMpA6j89cITN5Av__________gmlkgnY0gmlwhI5doAeJc2VjcDI1NmsxoQN5qMtXJ5IEyjGHjThv6KW44WSx_uQQWKjuewPSjofR5YhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo"
  - "enr:-MS4QMC7neI67z2PJJqUgAbMoUd34wvJv0MRTE3dsVpmQ_6ZT8rvmx_PA1qIWMsOi3c_t4NELwWD2Olok_JB5Fxa2FwIh2F0dG5ldHOIAAAAAAAAAACEZXRoMpA6j89cITN5Av__________gmlkgnY0gmlwhGj4FQSJc2VjcDI1NmsxoQK1tIIBHm-xguPgctpt1o2ILfvHVXnjabSrXmCVkRjS8YhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo"
  - "enr:-Ly4QA8iXpz0dVdG6BwQzB4TyMquF3yp-S1o07lKOTK11q8kHN8PCMekr4Cp9E1oddjOZlpkdoo_9ejDIw_pdbrD5SIKh2F0dG5ldHOI__________-EZXRoMpA6j89cITN5Av__________gmlkgnY0gmlwhGj4-xSJc2VjcDI1NmsxoQIeUvqs5QY4Xzw0F4IcyWADzqVPmwyZGNWit9kaNTwEH4hzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA"
  - "enr:-Ly4QLpPi6OUMjZ6RRfiHeygtz7-VejZUo2rP3cIJ6nanVyyRbUa7IoTiwyoQSREPf_yWhUdfzFXbZzuAMbimRNJe8URh2F0dG5ldHOI__________-EZXRoMpA6j89cITN5Av__________gmlkgnY0gmlwhKRcrjiJc2VjcDI1NmsxoQOxEed2yrhgQoOSj8CRYekwBjL3CqKk3OGu-n0dEE1xaohzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA"
  - "enr:-Ly4QPUWQ8u8SapC_ctgp0J_vLJiICcS9fC68zlwGFRjm96CN1hL6ROWy1nMuVhRjktojP94wAkijA6YDjvxqu57S-4gh2F0dG5ldHOI__________-EZXRoMpA6j89cITN5Av__________gmlkgnY0gmlwhI5draqJc2VjcDI1NmsxoQIenCOXg6YBLikBLLuBOCfPHmZf3yZxUy0CvmqTI4jdpYhzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA"
  - "enr:-Ly4QOoKDGZNwx-5JdfmPbdTe12w9Fpkq1KWLAQS2FvNfu0bXpgLVE7pa0LHD47gPxmzQ7KO_rwj26JMl851kHvuBikRh2F0dG5ldHOI__________-EZXRoMpA6j89cITN5Av__________gmlkgnY0gmlwhLKAy_OJc2VjcDI1NmsxoQN-4TLyfl1hShy_FYxbQyebZd7-ntt7Dtn90z-RshrX_IhzeW5jbmV0cw-DdGNwgiMog3VkcIIjKA"
el_bootnode_enode:
  - "enode://1ddbf101b687051a9c2d7202580cf4687b7548736bd039b3be881ac29e6da9d5d626a389e4a03699be67c0f043d3abae923c3d1915808e94dd2904d840f5b7d9@46.101.126.45:30303"
  - "enode://6701dd08e00ec90c88f698ae44599932a7e571f1871afad1b755c53f695da46257c2a4ed6ab7a2fa95409a5620f224cf0c2ce09b7e4b63f6be868290573f52fa@142.93.96.100:30303"
  - "enode://2f6671ebef9725a9c4cdc7ab81338b47d23d77f61ec4d34ca023f10c5993d7a40b10eaa0ab7e89ab8574f39fbc1906da64fc78e461f4a44e512c677d84a48fa0@178.128.206.76:30303"
  - "enode://10254b2c7280ed6a5993fc93d51dfa6d16f03cd57ff7bf9da4f06b705c5a95d7fe60b9acf27ddbe815ed07aee6af69d60df08fddd584640652f6a93de85da442@142.93.160.7:30303"
  - "enode://ec9960aa383372f0f17f4c727ff72dbc2fd42e401c8661e322a6c2155e0a8513fb9c96b6d45b1fa690d7bc44a2c7f1d94beae6a649ed629cd790e53829ae434b@104.248.21.4:30303"
  - "enode://a556250513722a903f92991fbc92fba5f1d147e47307c247ee780740183540ebc57dc09018eb7ad6d2e66194bd4e5263e6fcd0220b9bf99494ce44d62a770f62@104.248.251.20:30303"
  - "enode://6698b583a77907ad2d5b4da7ee9c2e2da05afbe68c4132c11e615537bd2c2fdbbd82e0b27ad0b75bff4d0d6a15e8b837c94ad46cd654e6913de77a5509f27ad1@164.92.174.56:30303"
  - "enode://a69fa8b49f70ff9a8f89ad0b091df1e4af0ea185aa1cae6652164f6880ec49866abfb0870e3855440233ce4f0f30cfdced90ca0557578c55cd3bafad9414ad2d@142.93.173.170:30303"
  - "enode://727181c78a888fc33084fec081723cba12bbeb859d6eaad3c3bb24fa4861e13eb30fdd17472c399035d440ffa66e50f5c85e6c0a0256d92797d05f513407d977@178.128.203.243:30303"
##############################################
# metric information
##############################################
# enter pushgateway config if needed
prometheus_config_file: "prometheus/prometheus.yml.j2"
push_url: "https://example.test/insert/0/prometheus/api/v1/write"
push_metrics_enabled: false
remote_write_auth: false
eth_metrics_exporter_enabled: false
cl_validator_metrics_enabled: false
eth_metrics_exporter_name: "metrics-exporter"
eth_metrics_exporter_image: "samcm/ethereum-metrics-exporter:0.17.0"
remote_write_username: "test"
remote_write_password: "test"

no_validator_keys: false
ethstats_url: "example.io"
ethstats_password: "example"

##############################################
# mev boost configs
##############################################
mev_boost_image_name: flashbots/mev-boost:v0.8.2
mev_boost_container_name: mev_boost
mev_boost_start_args: "-genesis-fork-version 0x00 -relays http://example.io"
mev_boost: false

##############################################
# ports to configure
##############################################
el_rpc_port: 8545
el_ws_rpc_port: 8546
el_engine_port_no_auth: 8550
el_engine_port: 8551
el_engine_snoop_port: 8560
el_engine_ws_port: 8552
nimbus_rpc_port: 4009
beacon_api_port: 4000
beacon_grpc_port: 4001
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
node_exporter_web_listen_address: "127.0.0.1:9100"
prometheus_web_listen_address: "127.0.0.1:9101"
el_metrics_port: 8002
eth_metrics_exporter_port: 8003
mev_boost_port: 18550

##############################################
# Command for JSON RPC snooper
##############################################
snoop_image_name: parithoshj/json_rpc_snoop:v1.0.0-x86
snoop_container_name: snooper

##############################################
# name of the validator to display
##############################################
graffiti: "{{cl_client_name}}-{{el_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
local_cl_config_filepath: "{{local_custom_config_data_host_dir}}/config.yaml"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}"
local_validator_host_archive: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}.tar.gz"

##############################################
# remote host data directories
##############################################
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"
testnet_dir: "{{home_dir}}/custom_config_data"
el_node_dir: "{{home_dir}}/eldata"

##############################################
# common log config
##############################################
beacon_log_level: info
common_log_options:
  max-file: "10"
  max-size: 500m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file

##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
execution_container_name: execution
hi_peer_count: 25
separate_validator_process_enabled: true

firewall_allowed_tcp_ports:
  - 22
  - 30303
  - 9000
  - 80
  - 443

firewall_allowed_udp_ports:
  - 30303
  - 9000

firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 8545 -s 46.101.126.45 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8546 -s 46.101.126.45 -j ACCEPT"