ansible_user: root

#beaconchain_explorer_aio_docker_image_default: skylenet/eth2-beaconchain-explorer:fix-frontend@sha256:1f3d059a74d691b06bb73a29f27786e2807d315d2d82093c81525ca18959f263

beaconchain_explorer_aio_url_erigon: http://167.71.56.106:8545
beaconchain_explorer_aio_url_erigon_ws: ws://167.71.56.106:8546
beaconchain_explorer_aio_url_geth: http://167.71.56.106:8545

beaconchain_explorer_aio_cleanup_all: false

beaconchain_explorer_aio_config: |
  # All config options can be found in here: https://github.com/gobitfly/eth2-beaconchain-explorer/blob/master/types/config.go
  chain:
    #name: sepolia
    network: "withdrawal-test"
    slotsPerEpoch: 32
    secondsPerSlot: 12
    genesisTimestamp: 1669897500
    mainnet: false # hide mainnet staking pool etc. info
    minGenesisActiveValidatorCount: 1050
    phase0path: "/custom_configs/phase0.yml"
    altairPath: "/custom_configs/phase0.yml"
    altairForkEpoch: 0
    configPath: "/custom_configs/phase0.yml"
  readerDatabase:
    name: db
    host: beaconchain_postgres
    port: "5432"
    user: postgres
    password: "pass"
  writerDatabase:
    name: db
    host: beaconchain_postgres
    port: "5432"
    user: postgres
    password: "pass"
  bigtable:
    project: explorer
    instance: beaconchain_bigtable:9000
  lastAttestationCachePath: "/data/lastAttestationCache"
  eth1ErigonEndpoint: "{{ beaconchain_explorer_aio_url_erigon }}"
  eth1GethEndpoint: "{{ beaconchain_explorer_aio_url_geth }}"
  redisCacheEndpoint: 'beaconchain_redis:6379'
  tieredCacheProvider: 'redis'
  frontend:
    siteDomain: "localhost:8080"
    siteName: "Beaconchain Explorer"
    siteSubtitle: "Testnet"
    server:
      host: '0.0.0.0' # Address to listen on
      port: '8080' # Port to listen on
    readerDatabase:
      name: db
      host: beaconchain_postgres
      port: "5432"
      user: postgres
      password: "pass"
    writerDatabase:
      name: db
      host: beaconchain_postgres
      port: "5432"
      user: postgres
      password: "pass"
    sessionSecret: "11111111111111111111111111111111"
    jwtSigningSecret: "1111111111111111111111111111111111111111111111111111111111111111"
    jwtIssuer: "localhost"
    jwtValidityInMinutes: 30
    maxMailsPerEmailPerDay: 10
    mail:
      mailgun:
        sender: no-reply@localhost
        domain: mg.localhost
        privateKey: "key-11111111111111111111111111111111"
    csrfAuthKey: '1111111111111111111111111111111111111111111111111111111111111111'
  indexer:
    indexMissingEpochsOnStartup: true # Check for missing epochs and export them after startup
    #updateAllEpochStatistics: true
    #fixCanonOnStartup: true
    #fullIndexOnStartup: true
    #checkAllBlocksOnStartup: true
    node:
      host: "10.19.0.27"
      port: '4000'
      type: lighthouse
    eth1DepositContractAddress: '0x4242424242424242424242424242424242424242'
    eth1DepositContractFirstBlock: 0


beaconchain_explorer_aio_extra_config_files:
  phase0.yml: |
    # Extends the mainnet preset
    PRESET_BASE: 'mainnet'
    CONFIG_NAME: 'withdrawal-test' # needs to exist because of Prysm. Otherwise it conflicts with mainnet genesis
    # Genesis
    # ---------------------------------------------------------------
    # `2**14` (= 16,384)
    MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 2140
    # Mar-01-2021 08:53:32 AM +UTC
    # This is an invalid valid and should be updated when you create the genesis
    MIN_GENESIS_TIME: 1670598900
    GENESIS_FORK_VERSION: 0x10000040
    GENESIS_DELAY: 0
    # Forking
    # ---------------------------------------------------------------
    # Some forks are disabled for now:
    #  - These may be re-assigned to another fork-version later
    #  - Temporarily set to max uint64 value: 2**64 - 1
    # Altair
    ALTAIR_FORK_VERSION: 0x20000040
    ALTAIR_FORK_EPOCH: 0
    # Merge
    BELLATRIX_FORK_VERSION: 0x30000040
    BELLATRIX_FORK_EPOCH: 0
    TERMINAL_TOTAL_DIFFICULTY: 0
    TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
    TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615
    # Capella
    CAPELLA_FORK_VERSION: 0x40000040
    # LH flag needs to be set
    EIP4844_FORK_EPOCH: 18446744073709551615
    # Sharding
    SHARDING_FORK_VERSION: 0x03001020
    SHARDING_FORK_EPOCH: 18446744073709551615
    # Time parameters
    # ---------------------------------------------------------------
    # 12 seconds
    SECONDS_PER_SLOT: 12
    # 14 (estimate from Eth1 mainnet)
    SECONDS_PER_ETH1_BLOCK: 14
    # 2**8 (= 256) epochs ~27 hours
    MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 1
    # 2**8 (= 256) epochs ~27 hours
    SHARD_COMMITTEE_PERIOD: 1
    # 2**11 (= 2,048) Eth1 blocks ~8 hours
    ETH1_FOLLOW_DISTANCE: 12
    # Validator cycle
    # ---------------------------------------------------------------
    # 2**2 (= 4)
    INACTIVITY_SCORE_BIAS: 4
    # 2**4 (= 16)
    INACTIVITY_SCORE_RECOVERY_RATE: 16
    # 2**4 * 10**9 (= 16,000,000,000) Gwei
    EJECTION_BALANCE: 16000000000
    # 2**2 (= 4)
    MIN_PER_EPOCH_CHURN_LIMIT: 4
    # 2**16 (= 65,536)
    CHURN_LIMIT_QUOTIENT: 65536
    # Deposit contract
    # ---------------------------------------------------------------
    DEPOSIT_CHAIN_ID: 1337804
    DEPOSIT_NETWORK_ID: 1337804
    DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
    # Updated penalty values
    # ---------------------------------------------------------------
    # 3 * 2**24 (= 50,331,648)
    INACTIVITY_PENALTY_QUOTIENT_ALTAIR: 50331648
    # 2**6 (= 64)
    MIN_SLASHING_PENALTY_QUOTIENT_ALTAIR: 64
    # 2
    PROPORTIONAL_SLASHING_MULTIPLIER_ALTAIR: 2
    # Sync committee
    # ---------------------------------------------------------------
    # 2**9 (= 512)
    SYNC_COMMITTEE_SIZE: 512
    # 2**8 (= 256)
    EPOCHS_PER_SYNC_COMMITTEE_PERIOD: 256
    # Sync protocol
    # ---------------------------------------------------------------
    # 1
    MIN_SYNC_COMMITTEE_PARTICIPANTS: 1
    # SLOTS_PER_EPOCH * EPOCHS_PER_SYNC_COMMITTEE_PERIOD (= 32 * 256)
    UPDATE_TIMEOUT: 8192
    # Mainnet preset - Bellatrix
    # Updated penalty values
    # ---------------------------------------------------------------
    # 2**24 (= 16,777,216)
    INACTIVITY_PENALTY_QUOTIENT_BELLATRIX: 16777216
    # 2**5 (= 32)
    MIN_SLASHING_PENALTY_QUOTIENT_BELLATRIX: 32
    # 3
    PROPORTIONAL_SLASHING_MULTIPLIER_BELLATRIX: 3
    # Execution
    # ---------------------------------------------------------------
    # 2**30 (= 1,073,741,824)
    MAX_BYTES_PER_TRANSACTION: 1073741824
    # 2**20 (= 1,048,576)
    MAX_TRANSACTIONS_PER_PAYLOAD: 1048576
    # 2**8 (= 256)
    BYTES_PER_LOGS_BLOOM: 256
    # 2**5 (= 32)
    MAX_EXTRA_DATA_BYTES: 32
    # Minimal preset - Capella
    # Mainnet preset - Custody Game
    # Time parameters
    # ---------------------------------------------------------------
    # 2**1 (= 2) epochs, 12.8 minutes
    RANDAO_PENALTY_EPOCHS: 2
    # 2**15 (= 32,768) epochs, ~146 days
    EARLY_DERIVED_SECRET_PENALTY_MAX_FUTURE_EPOCHS: 32768
    # 2**14 (= 16,384) epochs ~73 days
    EPOCHS_PER_CUSTODY_PERIOD: 16384
    # 2**11 (= 2,048) epochs, ~9 days
    CUSTODY_PERIOD_TO_RANDAO_PADDING: 2048
    # 2**15 (= 32,768) epochs, ~146 days
    MAX_CHUNK_CHALLENGE_DELAY: 32768
    # Max operations
    # ---------------------------------------------------------------
    # 2**8 (= 256)
    MAX_CUSTODY_KEY_REVEALS: 256
    # 2**0 (= 1)
    MAX_EARLY_DERIVED_SECRET_REVEALS: 1
    # 2**2 (= 2)
    MAX_CUSTODY_CHUNK_CHALLENGES: 4
    # 2** 4 (= 16)
    MAX_CUSTODY_CHUNK_CHALLENGE_RESP: 16
    # 2**0 (= 1)
    MAX_CUSTODY_SLASHINGS: 1
    # Reward and penalty quotients
    # ---------------------------------------------------------------
    EARLY_DERIVED_SECRET_REVEAL_SLOT_REWARD_MULTIPLE: 2
    # 2**8 (= 256)
    MINOR_REWARD_QUOTIENT: 256
    # Mainnet preset - Phase0
    # Misc
    # ---------------------------------------------------------------
    # 2**6 (= 64)
    MAX_COMMITTEES_PER_SLOT: 64
    # 2**7 (= 128)
    TARGET_COMMITTEE_SIZE: 128
    # 2**11 (= 2,048)
    MAX_VALIDATORS_PER_COMMITTEE: 2048
    # See issue 563
    SHUFFLE_ROUND_COUNT: 90
    # 4
    # 4
    HYSTERESIS_QUOTIENT: 4
    # Needed by beaconchain explorer
    SLOTS_PER_EPOCH: 32
