##############################################
# generic pow-faucet info
##############################################
powfaucet_node_dir: "{{home_dir}}/powfaucet_data"
debug: false

##############################################
# captcha info
##############################################
powfaucet_hcaptcha_site_key: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/verkle/verkle-hcaptcha-site-key') }}"
powfaucet_hcaptcha_secret: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/verkle/verkle-hcaptcha-secret') }}"

##############################################
# pow-faucet config
##############################################
powfaucet_network_name: "Shandong"
powfaucet_share_reward: 250000000000000000
powfaucet_min_reward:   500000000000000000
powfaucet_max_reward: 20000000000000000000
powfaucet_secret: "SomethingRandom!"
powfaucet_rpc_url: https://rpc.shandong.ethdevops.io
powfaucet_private_key: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/verkle/verkle-faucet-key') }}"
powfaucet_tx_link: https://explorer.shandong.ethdevops.io/tx/{txid}
unit_name: "shanETH"

##############################################
# faucet container info
##############################################
powfaucet_container_name: powfaucet
powfaucet_image_name: pk910/powfaucet
powfaucet_volumes:
  - "{{powfaucet_node_dir}}:/config"
