##############################################
# generic ansible config information
##############################################
ansible_user: "devops"
bootstrap_user: "devops"
initial_remote_user: "root"

github_user_pubkeys:
  - parithosh
  - barnabasbusa
  - skylenet


ansible_python_interpreter: /usr/bin/python3
oh_my_zsh_config:
  PROMPT: "%{$fg[yellow]%}%n%{$fg[white]%}@%{$fg[red]%}%m%{$reset_color%} ${PROMPT}"

##############################################
# el endpoints
##############################################
# nimbus requires a websocket endpoint (http support unstable)
# note: also used for execution engine endpoint in nimbus
consensus_endpoint_nimbus: ws://127.0.0.1:8551
beacon_api_endpoint: "http://127.0.0.1:{{beacon_api_port}}"
elendpoint: http://127.0.0.1:8545

# Merge Engine endpoints
# TODO change IP?
# TODO: some engines might start using the 8550 port (or 8551 for ws)

##############################################
# testnet specific information
##############################################
testnet_type: custom
cl_network_name: busanet
chainID: 1337804
fee_recipient: "0xE7c180eAdA8f60D63e9671867b2e0CA2649207A8"
# enter bootnodes here if needed
bootnode_enrs:
  - "enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk"
  - "enr:-LK4QOQbpISsytPcCJ8SGJSFYgeeL0Iyzk9evAnk3K0hztYIcaAMR2BjGDLEVzXzO0X0c5uz0uj53quXB_ekckKyJR8Gh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDT1d9ZQAAAQAEAAAAAAAAAgmlkgnY0gmlwhKdHP-SJc2VjcDI1NmsxoQOxbmB4wiZOvrR1HUKUJusOxgYr7FkFWHAEkzDRN7C6KoN0Y3CCIyiDdWRwgiMo"
multiaddrs:
  - "/ip4/167.71.63.228/tcp/9000/p2p/16Uiu2HAmQbc8YqfLaK2LUdkhJv3sjKZ2V58qULmaCaXq2ecdbqQ5"
el_bootnode_enode:
  - "enode://e5f935a1245a3cc8599939f1415e59ae66b5f1186c8e7a2e69b7d521f33dfbf2893faf0ad56badcc8e29bb81bbcc9a06616a0ea7a8f9dd6e74985cd22bf8730f@167.71.63.228:30303"
el_static_enodes:
  - "enode://e5f935a1245a3cc8599939f1415e59ae66b5f1186c8e7a2e69b7d521f33dfbf2893faf0ad56badcc8e29bb81bbcc9a06616a0ea7a8f9dd6e74985cd22bf8730f@167.71.63.228:30303"
##############################################
# metric information
##############################################
# enter pushgateway config if needed
prometheus_config_file: "prometheus/prometheus.yml.j2"
push_url: "https://example.test/insert/0/prometheus/api/v1/write"
push_metrics_enabled: false
remote_write_auth: false
eth_metrics_exporter_enabled: false
cl_validator_metrics_enabled: false
eth_metrics_exporter_name: "metrics-exporter"
eth_metrics_exporter_image: "samcm/ethereum-metrics-exporter:0.16.5"
remote_write_username: "test"
remote_write_password: "test"

no_validator_keys: false
ethstats_enabled: false 
metrics_enabled: false
snapsync_enabled: false
ethstats_url: "example.io"
ethstats_password: "example"

##############################################
# mev boost configs
##############################################
mev_boost_image_name: flashbots/mev-boost:v0.8.2
mev_boost_container_name: mev_boost
mev_boost_start_args: "-genesis-fork-version 0x00 -relays http://example.io"
mev_boost: false

##############################################
# ports to configure
##############################################
el_rpc_port: 8545
el_ws_rpc_port: 8546
el_engine_port_no_auth: 8550
el_engine_port: 8551
el_engine_snoop_port: 8560
el_engine_ws_port: 8552
nimbus_rpc_port: 4009
beacon_api_port: 4000
beacon_grpc_port: 4001
beacon_metrics_port: 8000
beacon_p2p_port: 9000
validator_metrics_port: 8001
validator_rpc_port: 4002
node_exporter_web_listen_address: "127.0.0.1:9100"
prometheus_web_listen_address: "127.0.0.1:9101"
el_metrics_port: 8002
eth_metrics_exporter_port: 8003
mev_boost_port: 18550

##############################################
# Command for JSON RPC snooper
##############################################
snoop_image_name: parithoshj/json_rpc_snoop:v1.0.0-x86
snoop_container_name: snooper

##############################################
# name of the validator to display
##############################################
graffiti: "{{cl_client_name}}-{{el_client_name}}"

##############################################
# local data directories
##############################################
local_explorerdata_host_dir: "{{inventory_dir}}/../explorerdata"
local_explorerdata_host_archive: "{{inventory_dir}}/../explorerdata.tar.gz"
local_forkmondata_host_dir: "{{inventory_dir}}/../forkmondata"
local_forkmondata_host_archive: "{{inventory_dir}}/../forkmondata.tar.gz"
local_custom_config_data_host_dir: "{{inventory_dir}}/../custom_config_data"
local_custom_config_data_host_archive: "{{inventory_dir}}/../custom_config_data.tar.gz"
local_cl_config_filepath: "{{local_custom_config_data_host_dir}}/config.yaml"
# private dirs
# Validator assignments
local_validator_host_dir: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}"
local_validator_host_archive: "{{inventory_dir}}/../validator_prep/{{ansible_hostname}}.tar.gz"

##############################################
# remote host data directories
##############################################
beacon_node_dir: "{{home_dir}}/beacon"
validator_node_dir: "{{home_dir}}/validator"
testnet_dir: "{{home_dir}}/custom_config_data"
el_node_dir: "{{home_dir}}/eldata"

##############################################
# common log config
# Possible log levels: 
# silent, error, warn, info (default), debug, detail
##############################################
execution_log_level: info
beacon_log_level: info
common_log_options:
  max-file: "10"
  max-size: 500m
  mode: non-blocking
  max-buffer-size: 4m
common_log_driver: json-file


##############################################
# container names
##############################################
beacon_container_name: beacon
validator_container_name: validator
execution_container_name: execution
hi_peer_count: 100
separate_validator_process_enabled: true

firewall_allowed_tcp_ports:
  - 22
  - 3334
  - 30303
  - 9000
  - 80
  - 443
  - 8545

firewall_allowed_udp_ports:
  - 30303
  - 9000

firewall_flush_rules_and_chains: true

firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 8545 -s 172.16.0.0/12 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8546 -s 172.16.0.0/12 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 4000 -s 167.71.63.228 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8545 -s 167.71.63.228 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 8545 -s 81.206.101.77 -j ACCEPT"
  - "iptabels -A INPUT -p tcp --dport 8545 -s 89.20.160.117 -j ACCEPT"