certificates:
  beaconchain.sepolia.ethdevops.io:
    mode: http


haproxy_frontends:
  - name: host_sepolia_beacon
    address: beaconchain.sepolia.ethdevops.io
    backend: host_ropsten_beacon


haproxy_backend_servers:
  - name: host_sepolia_beacon
    address: 146.190.21.21:3333
    options: 'check fall 3 rise 2'

haproxy_stats_port: 8404
haproxy_user: devops
haproxy_group: devops
haproxy_stats_user: devops
haproxy_stats_password: "{{ lookup('pipe', 'keybase fs read /keybase/team/ethereum.devops/verkle/verkle-haproxy-key') }}"

haproxy_default_backend_name: host_ropsten_beacon
grafana_prometheus_network_name: explorernet

le_email: parithosh@ethereum.org
debian_certbot: false
